# Generated by Django 5.0.2 on 2024-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.IntegerField(max_length=32),
        ),
    ]
